name: Deploy snapshot

on:
  push:
    branches:
      - main

jobs:
  deploy-snapshot:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        name: Checkout code
      - uses: burrunan/gradle-cache-action@v1
        name: Deploy snapshot
        env:
          ORG_GRADLE_PROJECT_SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
          ORG_GRADLE_PROJECT_SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          ORG_GRADLE_PROJECT_SIGNING_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
          ORG_GRADLE_PROJECT_SIGNING_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
        with:
          job-id: snapshot
          arguments: publishMavenJavaPublicationToSonatypeRepository
