name: Deploy Release

on:
  push:
    tags:
      - 'v*'

jobs:
  deploy-release:
    runs-on: ubuntu-20.04
    if: startsWith(github.ref, 'refs/tags')
    steps:
      - uses: actions/checkout@v2
        name: Checkout code
      - uses: burrunan/gradle-cache-action@v1
        name: Deploy Release
        env:
          ORG_GRADLE_PROJECT_sonatypeUsername: ${{ secrets.SONATYPE_USERNAME }}
          ORG_GRADLE_PROJECT_sonatypePassword: ${{ secrets.SONATYPE_PASSWORD }}
          ORG_GRADLE_PROJECT_signingKey: ${{ secrets.GPG_PRIVATE_KEY }}
          ORG_GRADLE_PROJECT_signingPassphrase: ${{ secrets.GPG_PASSPHRASE }}
        with:
          job-id: release
          arguments: publishMavenJavaPublicationToSonatypeRepository
      - name: Build changelog
        id: github_release
        uses: metcalfc/changelog-generator@v1.0.0
        with:
          myToken: ${{ secrets.GITHUB_TOKEN }}
      - name: Create release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          body: ${{ steps.github_release.outputs.changelog }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
